apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: music-quote-db
data:
  POSTGRES_DB: demopostgresdb
  POSTGRES_USER: demopostgresadmin
  POSTGRES_PASSWORD: demopostgrespwd