apiVersion: v1
kind: Service
metadata:
  name: music-quote-db
  labels:
    app: music-quote-db
spec:
  ports:
  - port: 5432
    name: music-quote-db
  clusterIP: None
  selector:
    app: music-quote-db