version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: demopostgrespwd
      POSTGRES_USER: demopostgresadmin
      POSTGRES_DB: demopostgresdb
    ports:
      - 5432:5432
  app:
    build:
      context: ../
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: always
    links:
      - db
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://db:5432/demopostgresdb?user=demopostgresadmin&password=demopostgrespwd
    ports:
      - 8080:8080
