name: Docker Image CI

on:
  pull_request:
    types: [closed]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew buildl
      - name: Build the Docker image Quarkus JVM
        run: docker build -f src/main/docker/Dockerfile.jvm -t littlewing/music-quote-jvm:$(date +%s) .
#    - name: Build the Docker image Quarkus native
#      run: docker build -f src/main/docker/Dockerfile.native -t littlewing/music-quote-native:$(date +%s) .
