name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image Quarkus JVM
      run: docker build -f src/main/docker/Dockerfile.jvm -t littlewing/music-quote-jvm:$(date +%s) .
    - name: Build the Docker image Quarkus native
      run: docker build -f src/main/docker/Dockerfile.native -t littlewing/music-quote-native:$(date +%s) .
